remote_theme: fongandrew/hydeout

markdown:         kramdown
highlighter:      rouge

kramdown:
  parse_block_html: true
  auto_ids: true

title:            Leo Tsaousis
tagline:          'My blog'
# this appears after a dot on the tab title 

description:      'Security Consultant / Researcher'
url:              https://laripping.github.io
# this is used (at least) in the search

baseurl:          '/'

author:
  name:           'Leonidas Tsaousis'
  url:            https://twitter.com/laripping

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jemoji

sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

