remote_theme: fongandrew/hydeout

# Dependencies ------
markdown:         kramdown
highlighter:      rouge

kramdown:
  parse_block_html: true

# Setup --------------


# title:            Hydeout
title:            Leo Tsaousis
tagline:          'My blog'
# this appears after  dot on the tab title 

description:      'Security Consultant / Researcher'
#description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://laripping.github.io
# this is used (at least) in the search

baseurl:          '/'
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Leonidas Tsaousis'
  url:            https://twitter.com/laripping

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-toc
  - jemoji


# Sidebar link settings ------


sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

